//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW_173
{
    public partial class Products
    {
        public int Id { get; set; }

        public string Group { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }

        public override string ToString()
        {
            return $"{Group} - {ProductName}";
        }
    }
}
